package com.staticum.niagaralauncher.ui.home

/** Short zen / minimalist phrases shown once each time Home enters composition. */
object ZenQuotes {
    private val minimalPhrases = listOf(
        "Menos, pero mejor.",
        "La quietud también es movimiento.",
        "Simplifica: lo esencial ya está ahí.",
        "Un solo respiro basta para empezar de nuevo.",
        "El espacio vacío también tiene forma.",
        "No hagas más. Haz lo que importa.",
        "La calma no se busca, se hace espacio para ella.",
        "Menos ruido, más presencia.",
        "Lo simple no es pobre, es claro.",
        "Cada cosa en su lugar, y nada de más.",
        "El silencio también responde.",
        "Ordena el espacio y la mente sigue.",
        "Vive con lo que eliges, no con lo que sobra.",
        "La atención es el lujo más simple.",
        "Deja ir lo que no necesitas hoy.",
        "Un momento a la vez es suficiente.",
        "La belleza está en lo que decides no tener.",
        "Respira antes de decidir.",
        "Lo esencial rara vez grita.",
        "El vacío no es ausencia, es posibilidad.",
        "Hoy, elige menos.",
        "La mente clara empieza en un espacio claro.",
        "No necesitas todo. Necesitas lo justo.",
        "La prisa rara vez mejora una decisión.",
        "Quita una cosa más de lo que crees necesario.",
        "El orden externo calma el ruido interno.",
        "Nada urge tanto como parece a las ocho de la mañana.",
        "Un espacio despejado piensa mejor que uno lleno.",
        "La quietud no es vacío, es claridad.",
        "Guarda lo que usas. Suelta lo que guardas.",
        "Menos decisiones, más presencia en cada una.",
        "El presente no necesita ser llenado, solo habitado.",
        "Lo que no eliges también te elige a ti.",
        "Una tarea a la vez es una forma de respeto.",
        "El ruido se acumula; la calma se elige.",
        "No todo lo que brilla merece tu atención.",
        "La simplicidad es una decisión diaria.",
        "Cada no despeja espacio para un sí mejor.",
        "El silencio antes de responder también es respuesta.",
        "Lo que no usas en un año, ya eligió irse.",
        "Un escritorio vacío no es pereza, es enfoque.",
        "La calma es una habilidad, no un estado de ánimo.",
        "No hay que llenar cada minuto para que valga.",
        "Menos pestañas abiertas, más pensamiento claro.",
        "El descanso también es parte del trabajo.",
        "Lo simple perdura; lo complicado se rompe primero.",
        "Elegir poco es elegir con cuidado.",
        "La calma se nota en lo que decides ignorar.",
        "Un día ligero empieza con una lista corta.",
        "Guardar todo es no decidir nada.",
        "La atención dividida no es atención.",
        "El espacio que dejas vacío también comunica.",
        "No busques más tiempo; usa mejor el que tienes.",
        "Un solo objetivo hoy es más honesto que diez.",
        "La costumbre de acumular empieza sin darse cuenta.",
        "El silencio de la mañana no necesita sonido de fondo.",
        "Menos opciones, decisiones más rápidas y mejores.",
        "Lo esencial se reconoce por lo que sobrevive al filtro.",
        "Una respiración lenta cambia el resto del día.",
        "No hay que tener razón, basta con estar en paz.",
        "El desorden visual pesa aunque no se note.",
        "Hazlo simple primero; complícalo solo si es necesario.",
        "Un solo paso claro vale más que diez posibles.",
        "La calma no llega, se construye con hábitos pequeños.",
        "Menos cosas que cuidar, más tiempo para vivir.",
        "El espacio que no llenas es también un regalo.",
        "Aprender a decir no es aprender a decir sí a algo mejor.",
        "La mente descansa cuando el entorno no le exige nada.",
        "No es tener menos por tener menos, es tener lo que importa.",
        "Un momento de quietud rinde más que una hora apurada.",
        "Lo urgente rara vez es lo importante.",
        "La simplicidad no resta valor, lo concentra.",
        "Guarda silencio antes de llenar el silencio.",
        "El primer paso del día define el resto.",
        "Menos ruido visual, más espacio para pensar.",
        "Lo que no decides hoy, decide por ti mañana.",
        "Una pausa breve también es progreso.",
        "El orden no es rigidez, es libertad para lo importante.",
        "No hace falta más para sentirse en paz, hace falta menos.",
        "La calma se practica, no se espera.",
        "Cada objeto que guardas pide un poco de tu atención.",
        "Lo simple se explica en una frase; lo confuso, en diez.",
        "Un día bien vivido no necesita estar lleno.",
        "La quietud de hoy es la claridad de mañana.",
        "Menos ambición de más, más atención a lo presente.",
        "El silencio también organiza el pensamiento.",
        "No compitas por llenar el tiempo, elige cómo usarlo.",
        "Un espacio limpio invita a una mente limpia.",
        "La paciencia es una forma silenciosa de disciplina.",
        "Menos multitarea, más presencia real.",
        "Lo que sueltas hoy deja espacio para lo que importa mañana.",
        "El descanso también produce, solo que en silencio.",
        "Una decisión clara vale más que diez posibles.",
        "La calma no es ausencia de movimiento, es dirección clara.",
        "Menos cosas por hacer, más cosas bien hechas.",
        "El espacio vacío en la agenda también es productivo.",
        "No hay que apurar la calma, solo permitirla.",
        "Lo esencial no compite por tu atención, la merece.",
        "Un solo foco a la vez rinde más que varios a medias.",
        "La simplicidad bien pensada nunca se siente pobre.",
        "El silencio de la mente empieza por el silencio del entorno.",
        "Menos, siempre que sea con intención.",
    )

    /** Stoic phrases and paraphrased quotes (Marco Aurelio, Séneca, Epicteto),
     * translated/adapted to Spanish and trimmed to the same short, unattributed
     * format as the rest of the list - the point is the thought landing in one
     * glance, not a citation. */
    private val stoicPhrases = listOf(
        "Tienes poder sobre tu mente, no sobre los eventos externos.",
        "No busques que las cosas pasen como quieres; desea que pasen como pasan.",
        "La felicidad de tu vida depende de la calidad de tus pensamientos.",
        "Lo que no mata mi carácter, no puede dañar mi vida.",
        "Mientras reaccionas, deja un espacio entre el estímulo y tu respuesta.",
        "No tienes que convertir esto en algo. No tiene por qué perturbarte.",
        "El obstáculo en el camino se convierte en el camino.",
        "Todo lo que escuches es una opinión, no un hecho. Todo lo que veas es una perspectiva, no la verdad.",
        "Si te aflige algo externo, no es eso lo que te perturba, sino tu juicio sobre ello.",
        "El que teme la muerte nunca hará nada digno de un ser vivo.",
        "Deja de dar vueltas. No vas a leer tus propios escritos, ni la historia de Roma, ni tus extractos de libros. Apúrate a vivir.",
        "No es el hombre que tiene poco el que es pobre, sino el que ansía más.",
        "Primero decide quién quieres ser. Luego haz lo que tengas que hacer.",
        "Haz cada acto de tu vida como si fuera el último.",
        "La riqueza consiste en ajustar los deseos, no en satisfacer todos.",
        "No actúes como si fueras a vivir diez mil años. La muerte está cerca.",
        "Confía en el tiempo lento: el carácter se construye repitiendo pequeñas elecciones, no en un solo gran día.",
        "Nadie es libre si no es dueño de sí mismo.",
        "La mejor venganza es no parecerte al que te hizo daño.",
        "Acepta lo que te suceda, aunque te parezca desagradable, porque te lleva hacia tu bien.",
        "No dejes que nada te tome por sorpresa; piensa de antemano en lo que puede salir mal.",
        "Un hombre sabio no sufre por lo que no tiene, sino que se alegra por lo que tiene.",
        "El que vive en armonía consigo mismo vive en armonía con el universo.",
        "No es que tengamos poco tiempo, sino que perdemos mucho.",
        "Todos los días nace alguien y ese día también se muere un poco.",
        "Dedica cada día a algo que puedas controlar; suelta el resto.",
        "El miedo nace de la anticipación, no de los hechos.",
        "Es difícil combinar y unir en un solo carácter el cuidado de uno mismo con el respeto a los demás.",
        "Cuando te levantes por la mañana, piensa en el privilegio que es estar vivo.",
        "La vida de un hombre necio está llena de ansiedad por el futuro y añoranza del pasado.",
        "No hay viento favorable para quien no sabe a qué puerto se dirige.",
        "La suerte es lo que sucede cuando la preparación encuentra la oportunidad.",
        "Si quieres mejorar, acepta ser visto como ignorante o tonto en algunas cosas.",
        "No te quejes de las espinas que tienen las rosas; alégrate de que los espinos tengan rosas.",
        "Lo que gobierna en nosotros, cuando está en armonía con la naturaleza, siempre elige el camino más fácil.",
        "El hombre que se enoja por algo no durará mucho enojado, si recuerda que todo en la vida es pasajero.",
        "Elige no ser dañado, y no te sentirás dañado. No te sientas dañado, y no lo estarás.",
        "No encontrarás tranquilidad fuera si primero no la tienes dentro.",
        "Nuestra vida es lo que nuestros pensamientos hacen de ella.",
        "Cada nuevo comienzo viene del final de otro comienzo.",
        "El obstáculo para la acción avanza la acción. Lo que se interpone en el camino se convierte en el camino.",
        "Un gema no se pule sin fricción, ni una persona se perfecciona sin pruebas.",
        "Piensa en toda la existencia, de la que eres una parte diminuta.",
        "No malgastes el resto de tu vida en pensamientos sobre los demás, cuando no sirven al bien común.",
        "La disciplina es elegir entre lo que quieres ahora y lo que quieres más.",
        "No es la muerte lo que un hombre debería temer, sino nunca haber empezado a vivir.",
        "Acepta las cosas a las que el destino te ata, y ama a las personas con quienes el destino te junta.",
        "Un buen carácter, cuando se mantiene firme, no necesita fortuna.",
        "Ningún hombre es libre si es esclavo de su cuerpo.",
        "La verdadera libertad es tener dominio sobre uno mismo.",
        "No es que seamos valientes porque no tenemos miedo, sino que actuamos a pesar de él.",
        "El sabio no busca el placer, sino la ausencia de dolor.",
        "El tiempo se te escapa mientras planeas lo que harás con él.",
        "Primero aprende a vivir bien. Luego aprende a morir bien.",
        "El que sufre antes de que sea necesario, sufre más de lo necesario.",
        "No hay nada bueno ni malo, sino el pensar lo hace así.",
        "Toda crueldad proviene de la debilidad.",
        "La fortuna favorece a los audaces.",
        "Lo que importa no es lo que te pasa, sino cómo reaccionas a ello.",
        "Haz lo correcto. El resto no importa.",
        "La ira es más dañina que la causa que la provocó.",
        "No hay viento que ayude a quien no sabe hacia dónde navega.",
        "El hombre sabio carga su riqueza dentro de sí mismo.",
        "Mantente firme como una roca contra la que rompen las olas.",
        "El universo es cambio; la vida es lo que nuestros pensamientos hacen de ella.",
        "Deja ir el apego a las cosas que no dependen de ti.",
        "Todo lo que existe es, en cierto sentido, la semilla de lo que surgirá.",
        "Actúa con justicia en cada momento, y habla con la verdad.",
        "Si no es correcto, no lo hagas. Si no es verdad, no lo digas.",
        "Mira hacia adentro. Ahí está la fuente del bien, siempre lista para brotar si siempre cavas.",
        "La mejor forma de vengarte es no ser como quien te hizo daño.",
        "Nada es tan destructivo para el carácter como una ocupación sin propósito.",
        "Es propio de un hombre sabio resistir el placer, y de un necio ser su esclavo.",
        "El tiempo cura lo que la razón no puede.",
        "El sabio no lamenta las oportunidades perdidas, sino que crea nuevas.",
        "Aprende a decir no cuando lo necesites, y a decirlo sin culpa.",
        "Tu mente tomará la forma de aquello en lo que la ejercites con frecuencia.",
        "No hay nada permanente excepto el cambio.",
        "Quien aprende a obedecer sabrá cómo mandar.",
        "Cuanto menos desees, más tendrás.",
        "Mide tu riqueza por lo que podrías dar, no por lo que tienes.",
        "Prepárate para lo peor, pero espera lo mejor.",
        "Un hombre sin mal temperamento es un hombre sin fuerza interior.",
        "El silencio es una fuente de gran fuerza.",
        "Vive hoy. El mañana es incierto, el ayer irrecuperable.",
        "Sé tolerante con los demás y estricto contigo mismo.",
        "No es lo que te sucede, sino cómo lo recibes, lo que importa.",
        "El carácter de un hombre se revela en cómo trata a quien no puede hacerle ningún bien.",
        "El dolor es inevitable; el sufrimiento es opcional.",
        "Aquel a quien se le teme, también teme a los demás.",
        "Nada sucede a quien no está preparado para enfrentarlo.",
        "El verdadero coraje es actuar sin certeza del resultado.",
        "Quien no tiene suficiente con poco, no tendrá suficiente con nada.",
        "La paciencia es una forma de acción.",
        "La adversidad revela el genio, la prosperidad lo oculta.",
        "Los hombres se perturban no por las cosas que pasan, sino por sus opiniones sobre ellas.",
        "No pidas que las cosas te sucedan como quieres, sino desea que sucedan como suceden.",
        "El alma que se gobierna a sí misma está en paz.",
        "Lo que no te hace mejor, te hace peor; no hay punto medio.",
        "El hábito de la reflexión diaria pule el carácter como el agua pule la piedra.",
        "Al final, lo que cuenta no es la duración de la vida, sino su profundidad.",
        "Sé como el promontorio contra el cual las olas siguen rompiéndose: él permanece y el oleaje se calma a su alrededor.",
        "El que teme sufrir, ya sufre por lo que teme.",
        "No hay camino fácil de la tierra a las estrellas.",
        "Quien se conoce a sí mismo es fuerte.",
        "El bien y el mal no suceden a quien tiene una voluntad recta.",
        "La verdadera grandeza está en ser dueño de uno mismo.",
        "Cultiva la indiferencia hacia lo que no puedes cambiar.",
    )

    private val phrases = minimalPhrases + stoicPhrases

    fun random(): String = phrases.random()
}
