package com.staticum.niagaralauncher.ui.home

/** Short zen / minimalist phrases shown once each time Home enters composition. */
object ZenQuotes {
    private val phrases = listOf(
        "Menos, pero mejor.",
        "La quietud también es movimiento.",
        "Simplifica: lo esencial ya está ahí.",
        "Un solo respiro basta para empezar de nuevo.",
        "El espacio vacío también tiene forma.",
        "No hagas más. Haz lo que importa.",
        "La calma no se busca, se hace espacio para ella.",
        "Menos ruido, más presencia.",
        "Lo simple no es pobre, es claro.",
        "Cada cosa en su lugar, y nada de más.",
        "El silencio también responde.",
        "Ordena el espacio y la mente sigue.",
        "Vive con lo que eliges, no con lo que sobra.",
        "La atención es el lujo más simple.",
        "Deja ir lo que no necesitas hoy.",
        "Un momento a la vez es suficiente.",
        "La belleza está en lo que decides no tener.",
        "Respira antes de decidir.",
        "Lo esencial rara vez grita.",
        "El vacío no es ausencia, es posibilidad.",
        "Hoy, elige menos.",
        "La mente clara empieza en un espacio claro.",
        "No necesitas todo. Necesitas lo justo.",
        "La prisa rara vez mejora una decisión.",
        "Quita una cosa más de lo que crees necesario.",
        "El orden externo calma el ruido interno.",
        "Nada urge tanto como parece a las ocho de la mañana.",
        "Un espacio despejado piensa mejor que uno lleno.",
        "La quietud no es vacío, es claridad.",
        "Guarda lo que usas. Suelta lo que guardas.",
        "Menos decisiones, más presencia en cada una.",
        "El presente no necesita ser llenado, solo habitado.",
        "Lo que no eliges también te elige a ti.",
        "Una tarea a la vez es una forma de respeto.",
        "El ruido se acumula; la calma se elige.",
        "No todo lo que brilla merece tu atención.",
        "La simplicidad es una decisión diaria.",
        "Cada no despeja espacio para un sí mejor.",
        "El silencio antes de responder también es respuesta.",
        "Lo que no usas en un año, ya eligió irse.",
        "Un escritorio vacío no es pereza, es enfoque.",
        "La calma es una habilidad, no un estado de ánimo.",
        "No hay que llenar cada minuto para que valga.",
        "Menos pestañas abiertas, más pensamiento claro.",
        "El descanso también es parte del trabajo.",
        "Lo simple perdura; lo complicado se rompe primero.",
        "Elegir poco es elegir con cuidado.",
        "La calma se nota en lo que decides ignorar.",
        "Un día ligero empieza con una lista corta.",
        "Guardar todo es no decidir nada.",
        "La atención dividida no es atención.",
        "El espacio que dejas vacío también comunica.",
        "No busques más tiempo; usa mejor el que tienes.",
        "Un solo objetivo hoy es más honesto que diez.",
        "La costumbre de acumular empieza sin darse cuenta.",
        "El silencio de la mañana no necesita sonido de fondo.",
        "Menos opciones, decisiones más rápidas y mejores.",
        "Lo esencial se reconoce por lo que sobrevive al filtro.",
        "Una respiración lenta cambia el resto del día.",
        "No hay que tener razón, basta con estar en paz.",
        "El desorden visual pesa aunque no se note.",
        "Hazlo simple primero; complícalo solo si es necesario.",
        "Un solo paso claro vale más que diez posibles.",
        "La calma no llega, se construye con hábitos pequeños.",
        "Menos cosas que cuidar, más tiempo para vivir.",
        "El espacio que no llenas es también un regalo.",
        "Aprender a decir no es aprender a decir sí a algo mejor.",
        "La mente descansa cuando el entorno no le exige nada.",
        "No es tener menos por tener menos, es tener lo que importa.",
        "Un momento de quietud rinde más que una hora apurada.",
        "Lo urgente rara vez es lo importante.",
        "La simplicidad no resta valor, lo concentra.",
        "Guarda silencio antes de llenar el silencio.",
        "El primer paso del día define el resto.",
        "Menos ruido visual, más espacio para pensar.",
        "Lo que no decides hoy, decide por ti mañana.",
        "Una pausa breve también es progreso.",
        "El orden no es rigidez, es libertad para lo importante.",
        "No hace falta más para sentirse en paz, hace falta menos.",
        "La calma se practica, no se espera.",
        "Cada objeto que guardas pide un poco de tu atención.",
        "Lo simple se explica en una frase; lo confuso, en diez.",
        "Un día bien vivido no necesita estar lleno.",
        "La quietud de hoy es la claridad de mañana.",
        "Menos ambición de más, más atención a lo presente.",
        "El silencio también organiza el pensamiento.",
        "No compitas por llenar el tiempo, elige cómo usarlo.",
        "Un espacio limpio invita a una mente limpia.",
        "La paciencia es una forma silenciosa de disciplina.",
        "Menos multitarea, más presencia real.",
        "Lo que sueltas hoy deja espacio para lo que importa mañana.",
        "El descanso también produce, solo que en silencio.",
        "Una decisión clara vale más que diez posibles.",
        "La calma no es ausencia de movimiento, es dirección clara.",
        "Menos cosas por hacer, más cosas bien hechas.",
        "El espacio vacío en la agenda también es productivo.",
        "No hay que apurar la calma, solo permitirla.",
        "Lo esencial no compite por tu atención, la merece.",
        "Un solo foco a la vez rinde más que varios a medias.",
        "La simplicidad bien pensada nunca se siente pobre.",
        "El silencio de la mente empieza por el silencio del entorno.",
        "Menos, siempre que sea con intención.",
    )

    fun random(): String = phrases.random()
}
